char *s = N_("Hide the indicator");
char *s = N_("Set background image");
char *s = N_("Set lock screen image");
char *s = N_("Download folder:");
char *s = N_("Commons Wallpaper pictures folder");
char *s = N_("Delete previously downloaded wallpapers:");
char *s = N_("Number of wallpapers to store before deleting oldest:");
char *s = N_("Hours between automatic updates:");
char *s = N_("Screen resolution:");
char *s = N_("Override automatic resolution selection");
char *s = N_("Settings");
char *s = N_("Gnome shell extension version:");
char *s = N_("Changes your wallpaper to selected pictures from Wikimedia Commons at set intervals. Displays the title, creator and license of the pictures.");
char *s = N_("Maintained by Jon Harald Søby");
char *s = N_("https://github.com/jhsoby/commons-wallpaper-gnome-extension");
char *s = N_("Based on the Bing Wallpaper Gnome extension by Michael Carroll, which was again based on the NASA APOD Gnome shell extension by Ella Argentieri.");
char *s = N_("<span size=\"small\">This program comes with ABSOLUTELY NO WARRANTY.\n"
             "See the <a href=\"https://www.gnu.org/licenses/old-licenses/gpl-2.0.html\">GNU General Public License, version 3 or later</a> for details.</span>");
char *s = N_("About");
